# Generated by Django 4.1 on 2022-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
