# Generated by Django 4.1 on 2022-08-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='position',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='stack',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='content',
        ),
        migrations.RemoveField(
            model_name='company',
            name='reward',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
