# Generated by Django 4.1 on 2022-08-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='posting',
        ),
    ]
